hpfeeds:
    image: andrewmichaelsmith/hpfeeds
    volumes:
      - var/hpfeeds:/vol/hpfeeds
    restart: always

kippo:
    image: andrewmichaelsmith/kippo
    volumes:
       - var/kippo:/vol/kippo
    ports:
       - "22:2222"
    restart: always
    working_dir: /vol/kippo
    links:
        - hpfeeds

dionaea:
    image: andrewmichaelsmith/dionaea
    volumes:
       - var/dionaea:/vol/dionaea
    links:
        - hpfeeds
    ports:
       - "21:21"
       - "42:42"
       - "80:80"
       - "135:135"
       - "443:443"
       - "445:445"
       - "1433:1433"
       - "3306:3306"
       - "5060:5060"
       - "5061:5061"
       - "69:69/udp"
       - "5060:5060/udp"
    restart: always
